In [3]:
import numpy as np

In [4]:
random_integers = np.random.randint(1, 101, size=10)

print("Random Integers:")
print(random_integers)

Random Integers:
[65 80 61  3 37 88  7 82 94 19]


In [6]:
#Generate Random Floating-Point Numbers
random_floats = np.random.rand(10)

print("Random Floating-Point Numbers:")
print(random_floats)

Random Floating-Point Numbers:
[0.66454396 0.9915872  0.78554882 0.67404101 0.00290734 0.80331748
 0.71656153 0.61767971 0.55704536 0.10613906]


In [7]:
#Generate Random Numbers Within a Range
random_numbers = np.random.uniform(10, 50, size=10)

print("Random numbers between 10 and 50:")
print(random_numbers)

Random numbers between 10 and 50:
[36.37273876 44.72289398 41.77428658 11.4761438  29.65271041 24.27947436
 42.84101121 13.86277888 32.65651476 47.22387543]


In [8]:
#Create a Small Simulated Dataset
student_marks = np.random.randint(35, 101, size=10)

print("Student Marks:")
print(student_marks)

Student Marks:
[95 52 53 98 90 77 48 49 95 76]


In [10]:
#Take Random Samples From an Array
students = np.array([
    "amir", "Priti", "Rahul", "Neha", "Geeha",
    "Rohan", "Pooja", "Akash", "Kiran", "Meena"
])

sample_students = np.random.choice(students, size=5, replace=False)

print("Random Student Sample:")
print(sample_students)

Random Student Sample:
['Neha' 'Kiran' 'Pooja' 'Meena' 'Akash']


In [11]:
#Demonstrate Random Seed
np.random.seed(42)

numbers1 = np.random.randint(1, 101, size=5)

print("First result:")
print(numbers1)

First result:
[52 93 15 72 61]


In [12]:
#Demonstrate Reproducibility
np.random.seed(42)

result1 = np.random.rand(5)

np.random.seed(42)

result2 = np.random.rand(5)

print("Result 1:")
print(result1)

print("\nResult 2:")
print(result2)

print("\nAre both results same?", np.array_equal(result1, result2))

Result 1:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Result 2:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Are both results same? True


In [13]:
#Generate a Random Student Dataset
np.random.seed(42)

student_ids = np.arange(1, 11)
marks = np.random.randint(35, 101, size=10)
attendance = np.random.randint(60, 101, size=10)

print("Student IDs:")
print(student_ids)

print("\nMarks:")
print(marks)

print("\nAttendance:")
print(attendance)

Student IDs:
[ 1  2  3  4  5  6  7  8  9 10]

Marks:
[86 49 95 55 58 37 56 87 36 64]

Attendance:
[97 61 80 92 71 81 84 86 87 75]


In [14]:
#Display Dataset
student_data = np.column_stack((student_ids, marks, attendance))

print("Student Dataset:")
print(student_data)

Student Dataset:
[[ 1 86 97]
 [ 2 49 61]
 [ 3 95 80]
 [ 4 55 92]
 [ 5 58 71]
 [ 6 37 81]
 [ 7 56 84]
 [ 8 87 86]
 [ 9 36 87]
 [10 64 75]]


In [15]:
#Random Choice From Dataset
np.random.seed(42)

selected_marks = np.random.choice(marks, size=5, replace=False)

print("Randomly Selected Marks:")
print(selected_marks)

Randomly Selected Marks:
[36 49 37 86 87]


In [16]:
#Final Example
np.random.seed(42)

data = np.random.randint(1, 101, size=20)

print("Generated Random Dataset:")
print(data)

sample = np.random.choice(data, size=5, replace=False)

print("\nRandom Sample:")
print(sample)

Generated Random Dataset:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38]

Random Sample:
[38  2 53 21 61]
